version: '3.5'

services:
  redis:
    image: 'redis:5-alpine'
    container_name: 'redis'
  pangalink:
    image: 'laurielias/pangalink'
    container_name: 'pangalink'
    build: .
    ports:
      - '8001:3480'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/home/pangalink/data
      - ./config:/home/pangalink/config